import { useCallback, useEffect, useRef, useState } from "react";
import { askCopilot, getCopilotStatus } from "../api/copilot";
import type { CopilotContext, CopilotResponse } from "../types/copilot";

const prompts = ["What's limiting recovery?", "Why are payments receiving DO_NOTHING?", "Show recent successful recoveries", "What happened to payment 107?"];

export function RecoveryCopilot({ open, onClose, context, initialPrompt }: { open: boolean; onClose: () => void; context: CopilotContext; initialPrompt?: string }) {
  const [message, setMessage] = useState(""); const [response, setResponse] = useState<CopilotResponse | null>(null);
  const [available, setAvailable] = useState<boolean | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const lastAutoPrompt = useRef("");
  useEffect(() => { getCopilotStatus().then(status => setAvailable(status.ai_available)).catch(() => setAvailable(false)); }, []);
  const ask = useCallback(async (text: string) => { if (!text.trim()) return; setMessage(text); setLoading(true); setError(""); try { setResponse(await askCopilot(text, context)); } catch { setError("Copilot could not reach the grounded data service."); } finally { setLoading(false); } }, [context]);
  useEffect(() => { if (open && initialPrompt && lastAutoPrompt.current !== `${initialPrompt}:${context.payment_id ?? context.optimization_payment_id ?? ""}`) { lastAutoPrompt.current = `${initialPrompt}:${context.payment_id ?? context.optimization_payment_id ?? ""}`; void ask(initialPrompt); } }, [ask, context.optimization_payment_id, context.payment_id, initialPrompt, open]);
  if (!open) return null;
  return <div className="copilot-backdrop" onMouseDown={onClose}><aside className="copilot-drawer" onMouseDown={event => event.stopPropagation()} aria-label="Recovery Copilot"><header><div><span className="copilot-spark">✦</span><div><strong>Recovery Copilot</strong><small>Grounded operations assistant</small></div></div><button onClick={onClose} aria-label="Close Recovery Copilot">×</button></header>{available === false && <div className="ai-unavailable"><b>AI Copilot unavailable</b><span>LLM provider not configured. Grounded deterministic explanations remain available.</span></div>}<div className="copilot-intro"><p>Ask about portfolio constraints, optimizer decisions, or persisted recovery history.</p><div>{prompts.map(prompt => <button key={prompt} onClick={() => void ask(prompt)}>{prompt}</button>)}</div></div><div className="copilot-conversation">{!response && !loading && !error && <div className="copilot-empty"><span>✦</span><p>Answers cite bounded RecoverIQ tools and never change financial decisions.</p></div>}{loading && <div className="copilot-thinking"><i/><span>Retrieving grounded facts…</span></div>}{error && <div className="copilot-error">{error}</div>}{response && !loading && <article className="copilot-answer"><div className="scope-pill">{response.data_scope}</div><p>{response.answer}</p>{response.facts.length > 0 && <section><strong>Supporting facts</strong>{response.facts.map(fact => <div key={fact.label}><span>{fact.label}</span><b>{fact.value}</b></div>)}</section>}<footer>Based on: {response.tools_used.join(" · ")}</footer></article>}</div><form onSubmit={event => { event.preventDefault(); void ask(message); }}><input value={message} maxLength={500} onChange={event => setMessage(event.target.value)} placeholder={context.payment_id ? `Ask about payment ${context.payment_id}…` : "Ask RecoverIQ…"}/><button disabled={loading || !message.trim()} aria-label="Send question">↑</button></form><p className="copilot-boundary">Read and explain only · Cannot execute or override decisions</p></aside></div>;
}
