from enum import Enum


class RecoveryAction(str, Enum):
    RETRY_NOW = "RETRY_NOW"
    RETRY_LATER = "RETRY_LATER"
    PAYMENT_LINK = "PAYMENT_LINK"
    ALTERNATE_METHOD = "ALTERNATE_METHOD"
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    INCENTIVE = "INCENTIVE"
    HUMAN_ESCALATION = "HUMAN_ESCALATION"
    DO_NOTHING = "DO_NOTHING"
