"""create initial schema

Revision ID: 139cf28b9e52
Revises: 
Create Date: 2026-08-30 13:33:06.880777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '139cf28b9e52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


recovery_action_enum = postgresql.ENUM(
    'RETRY_NOW',
    'RETRY_LATER',
    'PAYMENT_LINK',
    'ALTERNATE_METHOD',
    'WHATSAPP',
    'EMAIL',
    'INCENTIVE',
    'HUMAN_ESCALATION',
    'DO_NOTHING',
    name='recovery_action',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('external_customer_id', sa.String(length=255), nullable=False),
    sa.Column('successful_payments', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_payments', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('previous_recoveries', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_transaction_value', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_customer_id'), 'customers', ['external_customer_id'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_table('merchant_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('max_contacts', sa.Integer(), nullable=False),
    sa.Column('max_incentive', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('incentive_budget', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('minimum_margin', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('human_approval_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'FAILED', 'RECOVERED', 'SUCCEEDED', 'CANCELLED', name='payment_status'), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_failure_code'), 'payments', ['failure_code'], unique=False)
    op.create_index(op.f('ix_payments_merchant_id'), 'payments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    postgresql.ENUM(
        'RETRY_NOW',
        'RETRY_LATER',
        'PAYMENT_LINK',
        'ALTERNATE_METHOD',
        'WHATSAPP',
        'EMAIL',
        'INCENTIVE',
        'HUMAN_ESCALATION',
        'DO_NOTHING',
        name='recovery_action',
    ).create(op.get_bind(), checkfirst=True)
    op.create_table('recovery_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('selected_action', recovery_action_enum, nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('policy_status', sa.Enum('ALLOWED', 'REJECTED', 'REQUIRES_APPROVAL', name='policy_status'), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_decisions_payment_id'), 'recovery_decisions', ['payment_id'], unique=False)
    op.create_table('interventions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('action_type', recovery_action_enum, nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'EXECUTED', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='intervention_status'), nullable=False),
    sa.Column('intervention_cost', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('incentive_cost', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['recovery_decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interventions_decision_id'), 'interventions', ['decision_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=False),
    sa.Column('recovered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recovered_amount', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('recovery_time_hours', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intervention_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_interventions_decision_id'), table_name='interventions')
    op.drop_table('interventions')
    op.drop_index(op.f('ix_recovery_decisions_payment_id'), table_name='recovery_decisions')
    op.drop_table('recovery_decisions')
    recovery_action_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_merchant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_failure_code'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('merchant_policies')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_external_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('merchants')
    # ### end Alembic commands ###
