"""add intervention provider tracking

Revision ID: 7397f7def8ba
Revises: 7301c2e678bb
Create Date: 2026-09-01 23:24:19.012332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7397f7def8ba'
down_revision: Union[str, Sequence[str], None] = '7301c2e678bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interventions', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('interventions', sa.Column('provider_action_id', sa.String(length=255), nullable=True))
    op.add_column('interventions', sa.Column('provider_status', sa.String(length=100), nullable=True))
    op.add_column('interventions', sa.Column('last_provider_event_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_interventions_provider_action_id'), 'interventions', ['provider_action_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_provider_action_id'), table_name='interventions')
    op.drop_column('interventions', 'last_provider_event_at')
    op.drop_column('interventions', 'provider_status')
    op.drop_column('interventions', 'provider_action_id')
    op.drop_column('interventions', 'provider')
    # ### end Alembic commands ###
