import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getEvaluationAssignments, getEvaluationSummary } from "../api/evaluation";
import { InterventionActionBadge } from "../components/InterventionActionBadge";
import { MetricCard } from "../components/MetricCard";
import { PageHeader } from "../components/PageHeader";
import { SectionCard } from "../components/SectionCard";
import { LoadingSkeleton } from "../components/LoadingSkeleton";
import { StatusBadge } from "../components/StatusBadge";
import type { EvaluationAssignmentPage, EvaluationSummary } from "../types/evaluation";
import { formatINR, formatPercent } from "../utils/format";

const actions = ["", "RETRY_NOW", "RETRY_LATER", "PAYMENT_LINK", "ALTERNATE_METHOD", "WHATSAPP", "EMAIL", "INCENTIVE", "HUMAN_ESCALATION", "DO_NOTHING"];
const strategies = ["", "BASELINE", "ML_DECISION", "OPTIMIZED"];
const compactMoney = (value:number) => value >= 1_000_000 ? `₹${(value/1_000_000).toFixed(2)}M` : `₹${(value/1_000).toFixed(2)}K`;

export function EvaluationPage() {
  const [summary,setSummary]=useState<EvaluationSummary|null>(null), [assignments,setAssignments]=useState<EvaluationAssignmentPage|null>(null);
  const [loading,setLoading]=useState(true), [error,setError]=useState(""), [page,setPage]=useState(1), [search,setSearch]=useState(""), [action,setAction]=useState(""), [strategy,setStrategy]=useState("");
  const load=async()=>{setLoading(true);setError("");try{setSummary(await getEvaluationSummary())}catch{setError("The frozen evaluation artifacts could not be loaded.")}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  useEffect(()=>{const timer=setTimeout(()=>getEvaluationAssignments(page,search,action,strategy).then(setAssignments).catch(()=>setError("The assignment artifact could not be loaded.")),250);return()=>clearTimeout(timer)},[page,search,action,strategy]);
  if(loading)return <><PageHeader eyebrow="Research evidence" title="Offline Evaluation" description="Frozen 10,000-payment held-out synthetic test set"/><LoadingSkeleton/></>;
  if(error||!summary)return <><PageHeader eyebrow="Research evidence" title="Offline Evaluation" description="Frozen 10,000-payment held-out synthetic test set"/><div className="optimizer-error"><strong>Evaluation unavailable</strong><p>{error}</p><button onClick={()=>void load()}>Try again</button></div></>;
  const comparison=[{name:"Baseline",value:summary.baseline.net_recovery,note:"Synthetic fixed-rule baseline"},{name:"Unconstrained ML Benchmark",value:summary.unconstrained_ml.net_recovery,note:"Independent per-payment selection"},{name:"RecoverIQ Constrained",value:summary.recoveriq.net_recovery,note:"Feasible merchant-wide allocation"}], max=Math.max(...comparison.map(item=>item.value));
  const limits=[['Recovery spend',formatINR(summary.constraints.total_recovery_spend)],['Incentive budget',formatINR(summary.constraints.incentive_budget)],['Retry capacity',summary.constraints.retry_capacity.toLocaleString('en-IN')],['Contact capacity',summary.constraints.contact_capacity.toLocaleString('en-IN')],['WhatsApp capacity',summary.constraints.whatsapp_capacity.toLocaleString('en-IN')],['Incentive actions',summary.constraints.max_incentive_actions.toLocaleString('en-IN')],['Human escalations',summary.constraints.max_human_escalations.toLocaleString('en-IN')]];
  return <>
    <div className="evaluation-header"><PageHeader eyebrow="Research evidence" title="Offline Evaluation" description="Frozen 10,000-payment held-out synthetic test set"/><Link className="primary-cta" to="/recovery-queue">View Live Recovery <span>→</span></Link></div>
    <div className="evaluation-boundary"><b>SYNTHETIC OFFLINE EVALUATION</b><span>Decision-quality evaluation only. These values are not production merchant revenue.</span></div>
    <div className="metric-grid metric-grid-four"><MetricCard label="Baseline Net Recovery" value={compactMoney(summary.baseline.net_recovery)} note={`${formatINR(summary.baseline.net_recovery)} exact`}/><MetricCard label="RecoverIQ Net Recovery" value={compactMoney(summary.recoveriq.net_recovery)} note={`${formatINR(summary.recoveriq.net_recovery)} exact`} accent/><MetricCard label="Incremental Net Recovery" value={`+${compactMoney(summary.recoveriq.improvement)}`} note={`+${formatINR(summary.recoveriq.improvement)} vs baseline`} accent/><MetricCard label="Relative Improvement" value={`+${summary.recoveriq.relative_improvement_percent.toFixed(2)}%`} note="Constrained strategy vs baseline" accent/></div>
    <div className="rate-strip"><span>RECOVERY RATE</span><div>Baseline <b>{formatPercent(summary.baseline.recovery_rate*100)}</b></div><i>→</i><div>RecoverIQ <b>{formatPercent(summary.recoveriq.recovery_rate*100)}</b></div><strong>+{((summary.recoveriq.recovery_rate-summary.baseline.recovery_rate)*100).toFixed(2)} percentage points</strong></div>
    <SectionCard title="Strategy comparison" description="Frozen Phase 17 expected net recovery"><div className="evaluation-strategies">{comparison.map((item,index)=><div className={index===2?'evaluation-strategy selected':'evaluation-strategy'} key={item.name}><div><strong>{item.name}</strong><small>{item.note}</small></div><div className="evaluation-bar"><span style={{width:`${item.value/max*100}%`}}/></div><b>{formatINR(item.value)}</b></div>)}</div><p className="evaluation-explanation">The unconstrained ML benchmark selects independently per payment and does not respect merchant-wide resource limits. RecoverIQ trades some theoretical upside for a feasible portfolio allocation under budget and capacity constraints.</p></SectionCard>
    <div className="evaluation-two-col"><SectionCard title="Why constraints matter" description="Frozen evaluation limits"><div className="constraint-cards">{limits.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="solver-line"><span>Solver result</span><StatusBadge status={summary.recoveriq.solver_status}/><small>120,000 ms time limit</small></div><p className="evaluation-copy">RecoverIQ maximizes portfolio-level incremental net recovery while keeping the plan executable within merchant-defined operating limits.</p></SectionCard><SectionCard title="Dataset methodology" description="Synthetic, deterministic and held out"><div className="dataset-total"><span>Total synthetic records</span><strong>{summary.dataset.total_records.toLocaleString('en-IN')}</strong></div><div className="dataset-bar"><span style={{width:'64%'}}>Train · 32,000</span><span style={{width:'16%'}}>Validation · 8,000</span><span style={{width:'20%'}}>Frozen test · 10,000</span></div><p className="evaluation-copy">The 10,000-payment test set was held out from model training and used for final strategy evaluation. The dataset is synthetic and is not Razorpay production data.</p></SectionCard></div>
    <SectionCard title="Scale benchmark" description="Measured local planning runtime; not production traffic"><div className="compact-table benchmark-table"><table><thead><tr><th>Portfolio</th><th>Feature prep</th><th>ML</th><th>Policy / economics</th><th>Solver</th><th>Total</th><th>Status</th></tr></thead><tbody>{summary.scale_benchmarks.map(row=><tr key={row.payments}><td>{row.payments.toLocaleString('en-IN')} payments</td><td>{row.feature_prep_seconds.toFixed(4)}s</td><td>{row.ml_scoring_seconds.toFixed(4)}s</td><td>{row.policy_economics_seconds.toFixed(4)}s</td><td className="solver-time">{row.solver_seconds.toFixed(4)}s</td><td><strong>{row.total_seconds.toFixed(4)}s</strong></td><td><StatusBadge status={row.status}/></td></tr>)}</tbody></table></div><div className="benchmark-insight"><strong>At 10,000 payments, solver time is the dominant bottleneck.</strong><span>This points to merchant/batch partitioning, rolling optimization windows, candidate pruning, warm starts and time-bounded feasible solutions.</span></div></SectionCard>
    <SectionCard title="Assignment explorer" description={`${assignments?.artifact??'strategy_assignments.csv'} · real frozen artifact rows only`}><div className="plan-tools"><label><span>⌕</span><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search payment ID"/></label><select value={strategy} onChange={e=>{setStrategy(e.target.value);setPage(1)}}>{strategies.map(value=><option key={value} value={value}>{value||'All strategies'}</option>)}</select><select value={action} onChange={e=>{setAction(e.target.value);setPage(1)}}>{actions.map(value=><option key={value} value={value}>{value||'All actions'}</option>)}</select></div><div className="compact-table"><table><thead><tr><th>Payment</th><th>Strategy</th><th>Action</th><th>Amount</th><th>True recovery probability</th><th>Expected gross</th><th>Intervention cost</th><th>Incentive cost</th><th>Expected net</th></tr></thead><tbody>{assignments?.items.map(row=><tr key={`${row.payment_id}-${row.strategy}`}><td>#{row.payment_id}</td><td>{row.strategy}</td><td><InterventionActionBadge action={row.action}/></td><td>{formatINR(row.amount)}</td><td>{formatPercent(row.true_recovery_probability*100)}</td><td>{formatINR(row.expected_gross_revenue)}</td><td>{formatINR(row.intervention_cost)}</td><td>{formatINR(row.incentive_cost)}</td><td>{formatINR(row.expected_net_revenue)}</td></tr>)}</tbody></table></div><div className="plan-pagination"><span>{assignments?.total.toLocaleString('en-IN')??0} artifact rows · page {page}</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button disabled={!assignments||page*assignments.page_size>=assignments.total} onClick={()=>setPage(page+1)}>Next</button></div></div></SectionCard>
    <section className="evidence-boundary"><div><p className="eyebrow">How to interpret these results</p><h2>Three evidence boundaries, kept deliberately separate</h2></div><div><strong>Offline decision quality</strong><span>10,000 held-out synthetic payments</span><b>+4.14% constrained net recovery vs baseline</b></div><div><strong>System scale</strong><span>Planning benchmarked up to 10,000 payments</span><b>Measured local benchmark</b></div><div><strong>Live execution</strong><span>Provider-confirmed Test Mode outcomes live elsewhere</span><b>Recovery Batches + Audit Trail</b></div><Link className="primary-cta" to="/recovery-queue">Open Recovery Batches <span>→</span></Link></section>
  </>;
}
