import { useEffect, useState } from "react";
import { getInterventions } from "../api/interventions";
import { InterventionActionBadge } from "../components/InterventionActionBadge";
import { PageHeader } from "../components/PageHeader";
import { SectionCard } from "../components/SectionCard";
import { StatusBadge } from "../components/StatusBadge";
import type { InterventionLedgerPage } from "../types/intervention";
import { formatDateTime } from "../utils/format";

export function InterventionsPage() {
  const [data,setData]=useState<InterventionLedgerPage|null>(null),[page,setPage]=useState(1),[search,setSearch]=useState(""),[status,setStatus]=useState(""),[provider,setProvider]=useState(""),[error,setError]=useState("");
  useEffect(()=>{const timer=setTimeout(()=>{getInterventions({page,search,status,provider}).then(value=>{setData(value);setError("")}).catch(()=>setError("The intervention ledger could not be loaded."))},200);return()=>clearTimeout(timer)},[page,search,status,provider]);
  const pages=Math.max(1,Math.ceil((data?.total??0)/(data?.page_size??20)));
  return <><PageHeader eyebrow="Operations" title="Interventions" description="Track recovery actions from orchestration through provider execution and completion."/><SectionCard title="Execution ledger" description="Provider-aware intervention status"><div className="filter-bar"><label className="search-field"><input type="search" value={search} onChange={event=>{setSearch(event.target.value);setPage(1)}} placeholder="Search intervention or payment ID" aria-label="Search intervention or payment ID"/></label><select aria-label="Status" value={status} onChange={event=>{setStatus(event.target.value);setPage(1)}}><option value="">Status: All</option>{["PLANNED","EXECUTED","SUCCEEDED","FAILED","CANCELLED"].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Provider" value={provider} onChange={event=>{setProvider(event.target.value);setPage(1)}}><option value="">Provider: All</option><option value="razorpay">razorpay</option></select></div>{error&&<div className="inline-error"><span>!</span><p>{error}</p></div>}<div className="table-wrap"><table><thead><tr><th>Intervention ID</th><th>Payment ID</th><th>Action</th><th>Provider</th><th>Provider action ID</th><th>Provider status</th><th>Status</th><th>Executed at</th></tr></thead><tbody>{data?.items.map(item=><tr key={item.intervention_id}><td>#{item.intervention_id}</td><td>#{item.payment_id}</td><td><InterventionActionBadge action={item.action}/></td><td>{item.provider??"Internal"}</td><td>{item.provider_action_id??"—"}</td><td>{item.provider_status??"—"}</td><td><StatusBadge status={item.status}/></td><td>{item.executed_at?formatDateTime(item.executed_at):"—"}</td></tr>)}</tbody></table>{data&&!data.items.length&&<div className="table-empty"><strong>No interventions available</strong><p>Run an approved recovery workflow to create an intervention.</p></div>}<div className="table-footer"><span>{data?.total??0} results</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(page+1)}>Next</button></div></div></div></SectionCard></>;
}
