import { useEffect,useMemo,useState } from "react";
import { AllocationChart } from "../components/AllocationChart";
import { ConstraintForm } from "../components/ConstraintForm";
import { DecisionInspector } from "../components/DecisionInspector";
import { InterventionActionBadge } from "../components/InterventionActionBadge";
import { LoadingSkeleton } from "../components/LoadingSkeleton";
import { PageHeader } from "../components/PageHeader";
import { ResourceUtilization } from "../components/ResourceUtilization";
import { SectionCard } from "../components/SectionCard";
import { StatusBadge } from "../components/StatusBadge";
import { getDashboardOverview } from "../api/dashboard";
import { getOptimizationPortfolio,parseWhatIf,runOptimization } from "../api/optimization";
import type { OfflineStrategy } from "../types/dashboard";
import type { OptimizationConstraints,OptimizationResult,PlanAssignment,PortfolioMetadata,WhatIfChanges } from "../types/optimization";
import { formatINR,formatPercent } from "../utils/format";

const PAGE_SIZE=15;
export function OptimizationPage(){
 const [metadata,setMetadata]=useState<PortfolioMetadata|null>(null); const [constraints,setConstraints]=useState<OptimizationConstraints|null>(null); const [result,setResult]=useState<OptimizationResult|null>(null); const [frozen,setFrozen]=useState<OfflineStrategy[]>([]); const [solver,setSolver]=useState(""); const [loading,setLoading]=useState(true); const [running,setRunning]=useState(false); const [error,setError]=useState<string|null>(null); const [search,setSearch]=useState(""); const [action,setAction]=useState(""); const [page,setPage]=useState(1); const [selected,setSelected]=useState<PlanAssignment|null>(null); const [sort,setSort]=useState<"payment"|"value">("payment"); const [whatIf,setWhatIf]=useState(""); const [proposal,setProposal]=useState<WhatIfChanges|null>(null); const [parsing,setParsing]=useState(false); const [whatIfExplanation,setWhatIfExplanation]=useState("");
 const load=async()=>{setLoading(true);setError(null);try{const [portfolio,dashboard]=await Promise.all([getOptimizationPortfolio(),getDashboardOverview()]);setMetadata(portfolio);setConstraints(portfolio.default_constraints);setFrozen(dashboard.offline_evaluation.strategies);setSolver(dashboard.offline_evaluation.solver_status)}catch{setError("Could not load the optimization portfolio. Confirm that FastAPI and the model artifacts are available.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const optimize=async(nextConstraints=constraints)=>{if(!nextConstraints||running)return;setRunning(true);setError(null);try{const nextResult=await runOptimization(nextConstraints);setResult(nextResult);setPage(1);const binding=nextResult.resource_usage.filter(item=>item.limit>0&&item.used>=item.limit-1e-6).map(item=>item.label);const doNothing=nextResult.action_allocation.find(item=>item.action==="DO_NOTHING")?.count??0;setWhatIfExplanation(`The deterministic optimizer completed with ${doNothing.toLocaleString("en-IN")} DO_NOTHING assignments.${binding.length?` Binding resources: ${binding.join(", ")}.`:" No configured resource reached its limit."}`)}catch{setError("Optimization failed. Review constraints and backend logs, then retry.")}finally{setRunning(false)}};
 const interpretWhatIf=async()=>{if(!constraints||!whatIf.trim()||parsing)return;setParsing(true);setError(null);try{const parsed=await parseWhatIf(whatIf,constraints);setProposal(parsed.proposed_changes)}catch{setError("What-if interpretation was unavailable or invalid. No constraints were changed.")}finally{setParsing(false)}};
 const applyWhatIf=()=>{if(!constraints||!proposal)return;const next={...constraints,...proposal};setConstraints(next);setProposal(null);void optimize(next)};
 const filtered=useMemo(()=>{if(!result)return[];const rows=result.assignments.filter(item=>(!search||item.payment_id.toLowerCase().includes(search.toLowerCase()))&&(!action||item.action===action));return rows.sort((a,b)=>sort==="value"?b.incremental_value-a.incremental_value:a.payment_id.localeCompare(b.payment_id,undefined,{numeric:true}))},[result,search,action,sort]);
 const pageRows=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE); const pages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));
 if(loading)return <><PageHeader eyebrow="Portfolio intelligence" title="Portfolio optimization" description="Loading the frozen demo portfolio and merchant constraints."/><LoadingSkeleton/></>;
 if(!metadata||!constraints)return <><PageHeader eyebrow="Portfolio intelligence" title="Portfolio optimization" description="Allocate scarce recovery resources."/><div className="optimizer-error"><strong>Portfolio unavailable</strong><p>{error}</p><button onClick={()=>void load()}>Try again</button></div></>;
 const baseline=frozen.find(item=>item.strategy==="BASELINE"),optimized=frozen.find(item=>item.strategy==="OPTIMIZED"),ml=frozen.find(item=>item.strategy==="ML_DECISION");
 return <>
  <PageHeader eyebrow="Decision & resource allocation" title="Portfolio optimization" description="Allocate limited recovery resources across failed payments to maximize incremental net revenue."/>
  <div className="portfolio-banner"><div><span>Portfolio source</span><strong>{metadata.label}</strong><small>Offline records · real model scoring · real OR-Tools allocation</small></div><div><span>Eligible payments</span><strong>{metadata.payment_count.toLocaleString("en-IN")}</strong></div><div><span>Revenue at risk</span><strong>{formatINR(metadata.revenue_at_risk)}</strong></div><div><span>Execution boundary</span><strong>Plan only</strong><small>No Razorpay calls</small></div></div>
  <SectionCard title="What-if Recovery Copilot" description="Interpret merchant intent into a reviewable constraint proposal—never actions"><div className="what-if-input"><textarea value={whatIf} onChange={event=>setWhatIf(event.target.value)} placeholder="Today we're short staffed. Limit total recovery spend to ₹250, retries to 40…"/><button onClick={()=>void interpretWhatIf()} disabled={parsing||!whatIf.trim()}>{parsing?"Interpreting…":"Preview constraint changes"}</button></div>{proposal&&<div className="what-if-preview"><strong>Proposed merchant constraint changes</strong>{Object.entries(proposal).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><b>{constraints[key as keyof OptimizationConstraints].toLocaleString("en-IN")} → {Number(value).toLocaleString("en-IN")}</b></div>)}<p>No action has been selected or executed. The existing deterministic MILP runs only after confirmation.</p><div><button onClick={()=>setProposal(null)}>Cancel</button><button className="primary-cta" onClick={applyWhatIf}>Apply &amp; Optimize</button></div></div>}{whatIfExplanation&&<p className="what-if-explanation">{whatIfExplanation}</p>}</SectionCard>
  <SectionCard title="Merchant recovery constraints" description="Change a capacity and re-optimize to see the allocation respond"><ConstraintForm value={constraints} onFieldChange={(key,value)=>setConstraints(current=>current?{...current,[key]:value}:current)} onReset={()=>setConstraints(metadata.default_constraints)} onSubmit={()=>void optimize()} disabled={running} hasResult={Boolean(result)}/></SectionCard>
  {error&&<div className="inline-error"><span>!</span><p>{error}</p><button onClick={()=>void load()}>Reload portfolio</button></div>}
  {result&&<>
   <section className="result-hero"><div className="result-status"><span>Optimization complete</span><strong><i/>{result.status}</strong><small>{result.portfolio_label}</small></div><div><span>Portfolio</span><strong>{result.payment_count.toLocaleString("en-IN")}</strong><small>one action per payment</small></div><div><span>Baseline estimated net</span><strong>{formatINR(result.baseline_net_value)}</strong><small>{formatPercent(result.baseline_recovery_rate)} recovery</small></div><div className="hero-accent"><span>Optimized estimated net</span><strong>{formatINR(result.optimized_net_value)}</strong><small className={result.improvement_amount>=0?"delta-up":"delta-down"}>{result.improvement_amount>=0?"+":""}{formatINR(result.improvement_amount)} · {result.improvement_percent>=0?"+":""}{formatPercent(result.improvement_percent)}</small></div><div><span>Incremental objective</span><strong>{formatINR(result.total_incremental_value)}</strong><small>{formatPercent(result.expected_recovery_rate)} expected recovery</small></div></section>
   <div className="optimizer-two-col"><SectionCard title="Action allocation" description="DO_NOTHING remains a deliberate, visible decision"><AllocationChart items={result.action_allocation} total={result.payment_count}/></SectionCard><SectionCard title="Resource utilization" description={`${formatINR(result.intervention_spend)} used across constrained resources`}><ResourceUtilization items={result.resource_usage}/></SectionCard></div>
   <SectionCard title="Recovery plan" description="Click any row to inspect deterministic action economics"><div className="plan-tools"><label><span>⌕</span><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search payment ID"/></label><select value={action} onChange={e=>{setAction(e.target.value);setPage(1)}}><option value="">All actions</option>{result.action_allocation.map(item=><option key={item.action}>{item.action}</option>)}</select><button onClick={()=>setSort(sort==="payment"?"value":"payment")}>Sort: {sort==="payment"?"Payment ID":"Incremental value"}</button></div><div className="plan-table"><table><thead><tr><th>Payment</th><th>Amount</th><th>Assigned action</th><th>Predicted recovery</th><th>Incremental value</th><th>Intervention cost</th><th>Expected net</th><th>Policy</th></tr></thead><tbody>{pageRows.map(item=><tr key={item.payment_id} onClick={()=>setSelected(item)} tabIndex={0} onKeyDown={e=>e.key==="Enter"&&setSelected(item)}><td>#{item.payment_id}<small>{item.failure_type}</small></td><td>{formatINR(item.amount)}</td><td><InterventionActionBadge action={item.action}/></td><td>{formatPercent(item.recovery_probability*100)}</td><td className={item.incremental_value>=0?"positive-value":"negative-value"}>{formatINR(item.incremental_value)}</td><td>{formatINR(item.intervention_cost+item.incentive_cost)}</td><td>{formatINR(item.expected_net_value)}</td><td><StatusBadge status={item.policy_status}/></td></tr>)}</tbody></table></div><div className="plan-pagination"><span>{filtered.length.toLocaleString("en-IN")} assignments · page {page} of {pages}</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></div></div></SectionCard>
  </>}
  {!result&&!running&&<div className="optimizer-empty"><span>01</span><strong>Configure your operating limits.</strong><p>Then run the real predictive constrained optimizer to generate a portfolio plan. Nothing will be executed.</p></div>}
  {running&&result&&<div className="optimizing-overlay"><i/><span>Optimizing portfolio…</span><small>The previous result remains visible until the new plan is ready.</small></div>}
  <div className="data-label offline-label">OFFLINE MODEL EVALUATION <small>Frozen 10,000-payment held-out test set · unaffected by what-if controls</small></div>
  {baseline&&optimized&&<section className="frozen-benchmark"><div><span>Fixed-rule baseline</span><strong>{formatINR(baseline.net_value)}</strong><small>{formatPercent(baseline.recovery_rate)} recovery</small></div><i>→</i><div className="benchmark-winner"><span>RecoverIQ constrained optimizer</span><strong>{formatINR(optimized.net_value)}</strong><small>+{formatINR(optimized.uplift_amount)} · +{formatPercent(optimized.uplift_percent)}</small></div><div><span>Solver</span><strong>{solver}</strong><small>Constraints respected</small></div>{ml&&<div className="unconstrained"><span>Unconstrained predictive benchmark</span><strong>{formatINR(ml.net_value)}</strong><small>Upper benchmark · not production allocation</small></div>}</section>}
  {selected&&<DecisionInspector assignment={selected} onClose={()=>setSelected(null)}/>} 
 </>;
}
